# 配置mybatis数据源
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test?setTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 整合mybatis,实体类包配置和mapper映射地址
mybatis:
  type-aliases-package: com.changlu.springbootmybatis.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml